### ISSUE TITLE
Why your tips no effect

### ISSUE THREAD

**Issue by shijiebei2009** [wofeiwo/alfred-baidu-map#7]
![image](https://user-images.githubusercontent.com/4994697/42357796-310f29c4-810c-11e8-95ac-b6cb5497ea9a.png)

![image](https://user-images.githubusercontent.com/4994697/42357827-5b5c3848-810c-11e8-88d9-fbb0fd667035.png)
alfred 3.4[850] with powerpack.

**Comment by wofeiwo** [comment]
按下回车试一下呢？
下面显示是起点的选择。回车后应该会在网页版中给出路径的
